### ISSUE TITLE
Invalid XML

### ISSUE THREAD

**Issue by winfried** [tvgrabbers/tvgrabpyAPI#2] opened 2016-12-02 20:44 UTC
Every now and then the script procudes invalid XML. The file is invalid because there are unescaped quotes (") inside a XMP attribute. I have a hard time reproducing the bug, probably because it there is some interaction with the cache.

`winfried@miepie:/var/lib/mythtv$ xmllint pg.xml 
pg.xml:67062: parser error : attributes construct error
      <actor role="Burkhard Schulz "Butsch"">Götz Schubert</actor>
                                    ^
pg.xml:67062: parser error : Couldn't find end of Start Tag actor line 67062
      <actor role="Burkhard Schulz "Butsch"">Götz Schubert</actor>
`

the script runs normally, without errors, but mythfilldatabase doesn't want to eat the XML.

**Comment by hikavdh** [comment] 2016-12-02 21:36
Thanks! I found that too and found the cause. It will be fixed in the any day now coming next release, with also a lot of enhancements and fixes on ttvdb. It comes from quotes in the credits on primo.eu, that first broke the script on handling those credits and next weren't properly caught by the saxutils.

**Comment by hikavdh** [comment] 2016-12-02 21:39
The reproducing is difficult as first it is from a detail page, that isn't always there and second for as jet unknown reason the credits handling in the cache isn't doing what it should. I possibly have fixed that but testing is difficult.

**Comment by hikavdh** [comment] 2016-12-02 21:44
On Primo they place the name of the character between hooks. If that character has a nickname that is quoted and comma separated. I hadn't expected the commas that were taken as actor separations, breaking such an actor name in three. ;-)

**Comment by hikavdh** [comment] 2016-12-02 21:46
Next the character name  in xmltv comes as an attribute I forgot to handle with the saxutils.

**Comment by hikavdh** [comment] 2016-12-02 21:49
You perchance know of a graphic sqlite viewer? It makes checking and debugging the cache easier as I can without ad-hoc sql commands check the actual content.

**Comment by hikavdh** [comment] 2016-12-02 22:06
Forget that last one, I found two that are as we speak compiling. sqlitebrowser and sqliteman.

**Comment by hikavdh** [comment] 2016-12-04 22:02
The new 1.0.5 release is there: https://github.com/tvgrabbers/tvgrabpyAPI/releases/latest

**Closed by hikavdh** 2016-12-04 22:02 UTC
